## Import Numpy and Create a 2D NumPy Array

This code creates a **2D NumPy array** with 3 rows and 3 columns using `np.array()` and prints the array.

- **Rows:** 3
- **Columns:** 3
- **Shape:** `(3, 3)`

In [5]:
import numpy as np
arr= np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
]) 
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


## Calculate Row Mean

This code calculates the **mean (average) of each row** using `np.mean()`.

- `axis=1` → calculates the mean **row-wise**
- Result: `[20., 50., 80.]`

In [8]:
row_mean= np.mean(arr, axis=1)
print("Row mean: ", row_mean) 

Row mean:  [20. 50. 80.]


## Calculate Column Maximum

This code finds the **maximum value in each column** using `np.max()`.

- `axis=0` → calculates the maximum **column-wise**
- Result: `[70, 80, 90]`

In [9]:
column_max= np.max(arr, axis=0)
print("Column maxima: ", column_max)

Column maxima:  [70 80 90]


## Column-wise Min-Max Normalization

This code first finds the **minimum and maximum values of each column**, then applies **Min-Max normalization** to scale all column values between **0 and 1**.

- `axis=0` → calculates values column-wise
- Minimum value → `0`
- Maximum value → `1`
- Formula: `(arr - min) / (max - min)`

In [15]:
column_min = np.min(arr, axis=0)
column_max = np.max(arr, axis=0)

normalized = (arr - column_min) / (column_max - column_min)

## Display Original and Normalized Arrays

This code prints both the **original array** and the **normalized array** to compare their values before and after normalization.

In [14]:
print("Original array: \n", arr)
print("Normalised array: \n", normalised)

Original array: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Normalised array: 
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


## Calculate Column Means

This code calculates the **mean (average) of each column** using `np.mean()`.

- `axis=0` → calculates the mean column-wise
- `column_means` → stores the mean of each column
- For this array, the result is `[40., 50., 60.]`

In [19]:
column_means=np.mean(arr, axis=0)
print("Column means: ", column_means)

Column means:  [40. 50. 60.]


## Subtract Column Means

This code uses **broadcasting** to subtract the corresponding column mean from every element in the array.

- `arr - column_means` → subtracts each column's mean
- `result` → stores the mean-centered array
- Each column now has a mean of **0**

In [20]:
result= arr - column_means
print("Result: \n",result)

Result: 
 [[-30. -30. -30.]
 [  0.   0.   0.]
 [ 30.  30.  30.]]


## Multiply Array Using Loops

This code uses **nested loops** to multiply every element of the array by `2` and measures the execution time.

- `time.time()` → records the start and end time
- Nested loops → process each row and value individually
- `value * 2` → doubles each element
- `loop_time` → stores the time taken by the loop
- `result_loop` → stores the resulting array

In [28]:
import time
start= time.time()
result_loop=[]
for row in arr:
    new_row=[]
    for value in row:
        new_row.append(value*2)
    result_loop.append(new_row)
loop_time= time.time() - start
print("Loop result: \n", result_loop)
print("Loop time: \n", loop_time)

Loop result: 
 [[np.int64(20), np.int64(40), np.int64(60)], [np.int64(80), np.int64(100), np.int64(120)], [np.int64(140), np.int64(160), np.int64(180)]]
Loop time: 
 0.0013890266418457031


## Multiply Array Using Vectorization

This code uses **NumPy vectorization** to multiply every element of the array by `2` and measures the execution time.

- `arr * 2` → multiplies all elements by 2 at once
- `vectorized_time` → stores the time taken for the operation
- Vectorization is generally **faster and more efficient** than using Python loops.

In [29]:
start=time.time()
result_vectorized=arr*2
vectorized_time = time.time() - start
print("Vectorized result: \n", result_vectorized)
print("Vectorized time: ", vectorized_time)

Vectorized result: 
 [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
Vectorized time:  0.00012755393981933594


## Performance Comparison

The results show that **NumPy vectorization is faster** than using nested Python loops.

- **Loop time:** `0.001389` seconds
- **Vectorized time:** `0.000128` seconds
- Vectorization is approximately **11× faster** for this operation.

This demonstrates the performance advantage of using NumPy's built-in vectorized operations.

In [30]:
print("Loop time:", loop_time)
print("Vectorized time:", vectorized_time)

Loop time: 0.0013890266418457031
Vectorized time: 0.00012755393981933594
